### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence

### ISSUE THREAD

**Issue by dreamitpossible1** [EdjeElectronics/Image-Augmentation-Examples-for-Machine-Learning#1]
Traceback (most recent call last):
  File "augment_with_KPs.py", line 184, in <module>
    imgW_xml, imgH_xml, objects = read_annotation_data(xml_fn)
  File "augment_with_KPs.py", line 70, in read_annotation_data
    tree = ET.parse(file)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence

**Comment by EdjeElectronics** [comment]
This is probably an issue with your annotation data. You likely have unusual characters in your annotation files.

**Comment by EdjeElectronics** [comment]
Oops! This error can also happen if you specify the wrong file extension in the --imgext option. Make sure you use the correct file extension. I ran in to the same error because I used "--imgext=.jpg" rather than "--imgext=.JPG" . Using the capitalized .JPG resolved it.
