### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 15: character maps to <undefined>

### ISSUE THREAD

**Issue by mariohgu** [EdjeElectronics/Image-Augmentation-Examples-for-Machine-Learning#2]
Hello,
First of all, Thanks for your code.
I got this error when try to run the code. 

`File "C:\Users\user\Documents\Coding\TFODCourse\withaugem.py", line 184, in <module>
    imgW_xml, imgH_xml, objects = read_annotation_data(xml_fn)
  File "C:\Users\user\Documents\Coding\TFODCourse\withaugem.py", line 70, in read_annotation_data
    tree = ET.parse(file)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 15: character maps to <undefined>`

I already tried to set a encoding when open the file but I got this error.

`File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 4`

Thank you.

PD: This is my xml file.

```
<annotation>
	<folder>test</folder>
	<filename>CA00001.jpg</filename>
	<path>CA00001.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>832</width>
		<height>1096</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>danger</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>427</xmin>
			<ymin>204</ymin>
			<xmax>828</xmax>
			<ymax>349</ymax>
		</bndbox>
	</object>
	<object>
		<name>gun</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>671</xmin>
			<ymin>209</ymin>
			<xmax>829</xmax>
			<ymax>323</ymax>
		</bndbox>
	</object>
</annotation>
```

**Comment by mariohgu** [comment]
Hi... It is already solved.

I changed in the line 27: default='.jpg') #because my image extension is .jpg and by default it is set= .JPG

and in the line 209 changed: for n in range(int(NUM_AUG_IMAGES)):

That worked for me.

Thanks

**Comment by EdjeElectronics** [comment]
Hi @mariohgu, thanks for creating this issue and then updating it with your solution! The "`.jpg` vs `.JPG` thing is an annoying detail that I frequently get wrong 😮‍💨.

I'll change the code to make it so NUM_AUG_IMAGES is converted to integer also. Thanks again!
